### ISSUE TITLE
Unfullscreenize

### ISSUE THREAD

**Issue by Ploonet** [bazhenovc/fullscreenize#1]
Hi,

Your program has helped me out a lot.
However, I've fullscreenized a few windows by mistakes (qbittorrent for example), and I can't find a way to unfullscreenize them.
I tried : 
- Closing the program
- Force closing the program
- Rebooting my PC

It's a bit annoying because it prevents me from resizing the window, anchoring it to the sides, etc.

Any idea on how to fix it ?

I'm on Windows 10*

**Comment by bazhenovc** [comment]
Hi,

Sorry for the late reply, I didn't receive the notification for some reason.

Could you please provide more details about your environment? What window manager are you using?

**Comment by Ploonet** [comment]
Hi, thanks for the reply.
I have not modified the default Windows 10 window manager. The only difference I might have is that PowerToys fancy zones is installed.

I'm not sure what else to tell you, but my screen resolution is 3440:1440.

**Comment by bazhenovc** [comment]
Are you sure that this is the software you are looking for? The program in this repo doesn't support Windows at all, it's a Linux program.

**Comment by Ploonet** [comment]
I'm sorry, it has the same but you are correct, it's the wrong one. I'll close the issue, have a nice day.

**Comment by bazhenovc** [comment]
No problem at all, have a nice day too!
